# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/huang/experimental-projects/proto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/huang/experimental-projects/proto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huang/experimental-projects/proto/CMakeFiles /home/huang/experimental-projects/proto//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huang/experimental-projects/proto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shared_memory

# Build rule for target.
shared_memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shared_memory
.PHONY : shared_memory

# fast build rule for target.
shared_memory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_memory.dir/build.make CMakeFiles/shared_memory.dir/build
.PHONY : shared_memory/fast

#=============================================================================
# Target rules for targets named application

# Build rule for target.
application: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 application
.PHONY : application

# fast build rule for target.
application/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/build
.PHONY : application/fast

#=============================================================================
# Target rules for targets named network_communicator

# Build rule for target.
network_communicator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 network_communicator
.PHONY : network_communicator

# fast build rule for target.
network_communicator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_communicator.dir/build.make CMakeFiles/network_communicator.dir/build
.PHONY : network_communicator/fast

application.o: application.cpp.o
.PHONY : application.o

# target to build an object file
application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/application.cpp.o
.PHONY : application.cpp.o

application.i: application.cpp.i
.PHONY : application.i

# target to preprocess a source file
application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/application.cpp.i
.PHONY : application.cpp.i

application.s: application.cpp.s
.PHONY : application.s

# target to generate assembly for a file
application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/application.dir/build.make CMakeFiles/application.dir/application.cpp.s
.PHONY : application.cpp.s

network_communicator.o: network_communicator.cpp.o
.PHONY : network_communicator.o

# target to build an object file
network_communicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_communicator.dir/build.make CMakeFiles/network_communicator.dir/network_communicator.cpp.o
.PHONY : network_communicator.cpp.o

network_communicator.i: network_communicator.cpp.i
.PHONY : network_communicator.i

# target to preprocess a source file
network_communicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_communicator.dir/build.make CMakeFiles/network_communicator.dir/network_communicator.cpp.i
.PHONY : network_communicator.cpp.i

network_communicator.s: network_communicator.cpp.s
.PHONY : network_communicator.s

# target to generate assembly for a file
network_communicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_communicator.dir/build.make CMakeFiles/network_communicator.dir/network_communicator.cpp.s
.PHONY : network_communicator.cpp.s

src/services.o: src/services.cpp.o
.PHONY : src/services.o

# target to build an object file
src/services.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_communicator.dir/build.make CMakeFiles/network_communicator.dir/src/services.cpp.o
.PHONY : src/services.cpp.o

src/services.i: src/services.cpp.i
.PHONY : src/services.i

# target to preprocess a source file
src/services.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_communicator.dir/build.make CMakeFiles/network_communicator.dir/src/services.cpp.i
.PHONY : src/services.cpp.i

src/services.s: src/services.cpp.s
.PHONY : src/services.s

# target to generate assembly for a file
src/services.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/network_communicator.dir/build.make CMakeFiles/network_communicator.dir/src/services.cpp.s
.PHONY : src/services.cpp.s

src/shared_memory.o: src/shared_memory.cpp.o
.PHONY : src/shared_memory.o

# target to build an object file
src/shared_memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_memory.dir/build.make CMakeFiles/shared_memory.dir/src/shared_memory.cpp.o
.PHONY : src/shared_memory.cpp.o

src/shared_memory.i: src/shared_memory.cpp.i
.PHONY : src/shared_memory.i

# target to preprocess a source file
src/shared_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_memory.dir/build.make CMakeFiles/shared_memory.dir/src/shared_memory.cpp.i
.PHONY : src/shared_memory.cpp.i

src/shared_memory.s: src/shared_memory.cpp.s
.PHONY : src/shared_memory.s

# target to generate assembly for a file
src/shared_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shared_memory.dir/build.make CMakeFiles/shared_memory.dir/src/shared_memory.cpp.s
.PHONY : src/shared_memory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... application"
	@echo "... network_communicator"
	@echo "... shared_memory"
	@echo "... application.o"
	@echo "... application.i"
	@echo "... application.s"
	@echo "... network_communicator.o"
	@echo "... network_communicator.i"
	@echo "... network_communicator.s"
	@echo "... src/services.o"
	@echo "... src/services.i"
	@echo "... src/services.s"
	@echo "... src/shared_memory.o"
	@echo "... src/shared_memory.i"
	@echo "... src/shared_memory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

